export const errorConstants = {
  USER_ERROR: 'USER_ERROR',

  PRODUCTS_ERROR: 'PRODUCTS_ERROR',
  PRODUCT_ERROR: 'PRODUCT_ERROR',

  HISTORY_ERROR: 'HISTORY_ERROR',

  CATEGORIES_ERROR: 'CATEGORIES_ERROR',
  CATEGORY_ERROR: 'CATEGORY_ERROR',

  RESET_ERROR: 'RESET_ERROR'
};
