export const productsConstants = {
  GET_ALL_SUCCESS: 'PRODUCTS_GET_ALL_SUCCESS',
};

export const productConstants = {
  GET_SUCCESS: 'PRODUCT_GET_SUCCESS',
  ADD_SUCCESS: 'PRODUCT_ADD_SUCCESS',
  UPDATE_SUCCESS: 'PRODUCT_UPDATE_SUCCESS',
  DELETE_SUCCESS: 'PRODUCT_DELETE_SUCCESS',
};
