export const userConstants = {
  REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
  LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  GET_SUCCESS: 'USER_GET_SUCCESS',
  UPDATE_SUCCESS: 'USER_UPDATE_SUCCESS',
  DELETE_SUCCESS: 'USER_DELETE_SUCCESS',

  LOGOUT: 'USER_LOGOUT'
};
